@REM 
@REM        Table : 2020pattern0602_TestNewProgram.xlsx
@REM        Sheet : TEST_Reg_Read_Write
@REM Generated at : 2020/06/02 13:12:16
@REM Generated by : pattern_tool version Beta for FT J750 only 20190415 CY modify
@REM 
cleCY20191108.exe reg set 0x460224 0x08579487
cleCY20191108.exe reg getbits 0x460224 16 31
@REM check value : LLLLHLLLLHLHLHHH
cleCY20191108.exe reg getbits 0x460224 0 15
@REM check value : HLLHLHLLHLLLLHHH
cleCY20191108.exe reg set 0x460224 0xFFFFFFFF
cleCY20191108.exe reg getbits 0x460224 16 31
@REM check value : HHHHHHHHHHHHHHHH
cleCY20191108.exe reg getbits 0x460224 0 15
@REM check value : HHHHHHHHHHHHHHHH
cleCY20191108.exe reg set 0x460224 0
cleCY20191108.exe reg getbits 0x460224 16 31
@REM check value : LLLLLLLLLLLLLLLL
cleCY20191108.exe reg getbits 0x460224 0 15
@REM check value : LLLLLLLLLLLLLLLL
cleCY20191108.exe reg getbits 0x001620 0 15
@REM check value : LLLLLLLLLLHHLLLL
@pause
